# =====================================
# Build Stage
# =====================================
FROM node:22.22.0-alpine AS builder

WORKDIR /frontend

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN test -n "${VITE_API_BASE_URL}" || \
  (echo "VITE_API_BASE_URL is required" && exit 1)

RUN npm run build


# =====================================
# Runtime Stage
# =====================================
FROM nginx:alpine

COPY --from=builder /frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]