# =====================================
# Build Stage
# =====================================
FROM node:22.22.0-alpine AS builder

WORKDIR /frontend

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


# =====================================
# Runtime Stage
# =====================================
FROM nginx:alpine

COPY --from=builder /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]