server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Viteが生成した静的アセット
    location /assets/ {
        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # React Router用のSPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}