// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//削除推奨（本構成では不要）
import "dotenv/config";
import { defineConfig } from "prisma/config";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL, // migrate用
  },
});
